### ISSUE TITLE
Prelim modeling

### ISSUE THREAD

**Issue by ErikGreenJ** [jordanhowesnelson/west-nile-project-4#16]
This looks like a great start!  The scores are so good because we need to balance classes though, I failed to do this when cleaning and EDA.  Classes are balanced as follows:

0    0.947554
1    0.052446

-we'll need to fit to only the dummies and change lat/long to spatiotemporal too.

-once we start modeling, we need to score with roc_auc.  I'm going to come in a bit early tomorrow to take care of the balancing and work through a bit of weather df.

**Comment by jordanhowesnelson** [comment]
Added to the planning doc.
